version: '2'

services:

  bgdeploy-proxy:
    container_name: bgdeploy-proxy
    build:
      context: ./test-proxy
    ports:
      - 80:80
    depends_on:
      - bgdeploy-app
    environment:
        HOST_PORT: 80
        BACKEND_HOST_NAME: bgdeploy-app
        BACKEND_HOST_PORT: 8080

  bgdeploy-app:
    container_name: bgdeploy-app
    build:
      dockerfile: Dockerfile.debug
      context: ./test-app
    ports:
      - 8080:8080
    environment:
      HOST_PORT: 8080
    volumes:
      - ./test-app:/srv:cached